/* Action Types */
export const HANDLE_SIGN_IN = 'HANDLE_SIGN_IN';
export const HANDLE_SIGN_OUT = 'HANDLE_SIGN_OUT';
export const HANDLE_FETCH_STREAMS = 'HANDLE_FETCH_STREAMS';
export const HANDLE_FETCH_STREAM = 'HANDLE_FETCH_STREAM';
export const HANDLE_CREATE_STREAM = 'HANDLE_CREATE_STREAM';
export const HANDLE_EDIT_STREAM = 'HANDLE_EDIT_STREAM';
export const HANDLE_DELETE_STREAM = 'HANDLE_DELETE_STREAM';
